---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opt-bin
data:
  startup: |-
    #!/bin/sh
    #
    while true
    do
      sleep 10
      echo "waiting"
    done
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
stringData:
  password: mysecretpassword123
  secret.sh: |-
    #!/usr/bin/env bash
    echo "running a script"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod
  labels:
    app.kubernetes.io/name: TestApp
spec:
  containers:
    - name: primary
      image: library/busybox:latest
      command: ["sh"]
      args: ["/opt/bin/startup"]
      env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secrets
              key: password
      volumeMounts:
        - name: opt-bin
          mountPath: "/opt/bin/startup"
          subPath: startup
          readOnly: true
        - name: a-script
          mountPath: /opt/bin/secret.sh
          subPath: secret.sh
  volumes:
    - name: opt-bin
      configMap:
        name: opt-bin
    - name: a-script
      secret:
        secretName: my-secrets
  dnsPolicy: ClusterFirst
  restartPolicy: Always
