---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opt-bin
data:
  startup: |-
    #!/bin/sh
    #
    while true
    do
      sleep 10
      echo "waiting"
    done
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data01
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod
  labels:
    app.kubernetes.io/name: TestApp
spec:
  containers:
    - name: primary
      image: library/busybox:latest
      command: ["sh"]
      args: ["/opt/bin/startup"]
      volumeMounts:
        - name: opt-bin
          mountPath: "/opt/bin"
          readOnly: true
        - name: data
          mountPath: "/srv"
  volumes:
    - name: opt-bin
      configMap:
        name: opt-bin
    - name: data
      persistentVolumeClaim:
        claimName: data01
  dnsPolicy: ClusterFirst
  restartPolicy: Always
