---
apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: test
  # annotations:
  #   metallb.universe.tf/allow-shared-ip: "a-shared-ip"
spec:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  selector:
    app.kubernetes.io/name: test
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 2222
