---
apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: test
spec:
  selector:
    app.kubernetes.io/name: TestApp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
