apiVersion: v1
kind: Pod
metadata:
  name: data-copy
spec:
  containers:
  - name: copy-container
    image: busybox
    command: ["/bin/sh", "-c", "cp -r /source/* /target/ && sleep 3600"]
    volumeMounts:
    - name: source-volume
      mountPath: /source
    - name: target-volume
      mountPath: /target
  volumes:
  - name: source-volume
    persistentVolumeClaim:
      claimName: old-pvc
  - name: target-volume
    persistentVolumeClaim:
      claimName: new-pvc
  restartPolicy: Never
